---
- name: configure JupyterHub server
  # hosts: "{{hub_ip}}"
  hosts: localhost
  become: true
  vars_files:
  - vars.yaml
  tasks:

  - name: update packages
    apt:
      name: "*"
      state: latest

  - name: install system dependencies
    apt:
      pkg:
      - python3
      - python3-virtualenv
      - nodejs
      - npm

  - name: create virtualenv
    command: /usr/bin/env python3 -m virtualenv /opt/jupyterhub
    args:
      creates: /opt/jupyterhub

  - name: install python dependencies
    pip:
      name:
      - wheel
      - jupyterhub
      - jupyterlab
      - ipywidgets
      - jupyterhub-idle-culler
      - jupyterhub-systemdspawner
      virtualenv: /opt/jupyterhub

  - name: install configurable http proxy
    community.general.npm:
      name: configurable-http-proxy
      global: yes

  - name: create /opt/jupyterhub/etc
    file:
      path: /opt/jupyterhub/etc
      state: directory

  - name: create /opt/jupyterhub/etc/jupyterhub
    file:
      path: /opt/jupyterhub/etc/jupyterhub
      state: directory

  - name: jupyterhub_config
    copy:
      src: ./src/jupyterhub_config.py
      dest: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
      mode: 0600

  - name: create /opt/jupyterhub/etc/jupyter
    file:
      path: /opt/jupyterhub/etc/jupyter
      state: directory

  - name: jupyterhub_notebook_config
    copy:
      src: ./src/jupyterhub_notebook_config.py
      dest: /opt/jupyterhub/etc/jupyter/jupyterhub_notebook_config.py

  - name: create /etc/systemd/system/jupyterhub.service
    copy:
      src: ./src/jupyterhub.service
      dest: /etc/systemd/system/jupyter.service
      mode: 0755

  - name: start and enable jupyterhub service
    service:
      name: jupyterhub
      state: started
      enabled: yes

  - name: create /etc/nginx/sites-available/default
    copy:
      src: ./src/nginx-default
      dest: /etc/nginx/sites-available/default

  - name: symlink nginx conf
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: start and enable nginx service
    service:
      name: nginx
      state: started
      enabled: yes
